language: go
sudo: required
services:
- docker
go: 1.9
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/vendor
after_success: |
  bash <(curl -s https://codecov.io/bash)

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    make docker-push
    curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/viws
  fi
notifications:
  email: false
