language: go
sudo: required
services:
- docker
go:
- 1.7
install: make
script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- docker build -t ${DOCKER_USER}/http . &&
  docker push ${DOCKER_USER}/http
notifications:
  email: false
